name: user_support_mobile
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  animations: ^2.0.1
  cupertino_icons: ^1.0.2
  file_picker: ^4.0.0
  flutter:
    sdk: flutter
  flutter_slidable: ^0.6.0
  flutter_svg: ^0.22.0
  google_fonts: ^2.1.0
  http: ^0.13.3
  shimmer: ^2.0.0
  d2_touch: ^1.0.0-beta.9
  dio: ^4.0.4
  freezed_annotation: ^0.15.0
  intl: ^0.17.0
  provider: ^6.0.3
  reflectable: ^3.0.9
  go_router: ^4.3.0

dev_dependencies:
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter
  lint: ^1.5.3
  # freezed: ^0.15.1+1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
